homepage: "https://github.com/torvalds/linux.git"
language: c
primary_contact: "lukpirch@tu-bs.de"
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
  - dataflow
sanitizers:
  - address
  - undefined
  - dataflow
architectures:
  - x86_64
  - i386
main_repo: 'https://github.com/torvalds/linux.git'
